### ISSUE TITLE
Meilisearch reverse proxy

### ISSUE THREAD

**Issue by spookyuser** [typesense/typesense-website#60]
According to the comparison table [here](https://typesense.org/typesense-vs-algolia-vs-elasticsearch-vs-meilisearch/#:~:text=Requires%20use%20of%20nginx%2C%20apache%20or%20the%20like%20as%20a%20reverse%20proxy%20in%20front%2C%20before%20exposing%20to%20frontend) meilisearch requires a reverse proxy whereas typesense can run on a single binary with a high performance web server. However, meilisearch works fine without a reverse proxy perhaps it might be more secure with one but I've deployed it many times without ever using one, and in fact with just a single binary you can expose meiliesearch to the frontend.

**Comment by jasonbosco** [comment]
Hi @spookyuser, that was based on Meilisearch's docs, which suggest setting up an Nginx reverse proxy when running Meilisearch in production: ​https://docs.meilisearch.com/create/how_to/running_production.html

In general, any HTTP server can be exposed directly to the internet without a reverse-proxy - it will work, but things like connection pooling come into the picture at scale. I'm not sure if Meilisearch automatically handles this and/or if that's why the recommendation is to use nginx in front in production.
